### PR TITLE
DOCS SilverStripe and permission instructions

### PR DESCRIPTION
**Pull request by jsirish**

### CODE REVIEW

**Comment by jsirish** [comment]
Looked further into settings permissions via the Vagrant file, but didn't have much luck. This should be a good solution for that, and includes instructions to get up and running with SilverStripe.

Notice the serverpilot specific composer commands as well.

**Comment by muskie9** [comment]
- [x] Bump up the permissions/server group stuff
- [x] Add Gasmask reference
- [x] Mention we're using SilverStripe as the example framework, but it works with other mainstream frameworks.

**Comment by jsirish** [comment]
Just pushed an update, let me know if this covers the above

**Comment by muskie9** [comment]
Looks good.

**Pull request merged**
